//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Multiproducto.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTIPRODUCTOS_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MULTIPRODUCTOS_PRODUCTO()
        {
            this.MULTIPRODUCTOS_SOLICITUD = new HashSet<MULTIPRODUCTOS_SOLICITUD>();
        }
    
        public int productoid { get; set; }
        public string descripcion { get; set; }
        public string detalle1 { get; set; }
        public string detalle2 { get; set; }
        public string condicion { get; set; }
        public string masinf { get; set; }
        public Nullable<System.DateTime> vigencia { get; set; }
        public Nullable<int> segmento { get; set; }
        public Nullable<System.DateTime> fecreg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MULTIPRODUCTOS_SOLICITUD> MULTIPRODUCTOS_SOLICITUD { get; set; }
    }
}
