//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Multiproducto.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTIPRODUCTOS_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MULTIPRODUCTOS_CLIENTE()
        {
            this.MULTIPRODUCTOS_SOLICITUD = new HashSet<MULTIPRODUCTOS_SOLICITUD>();
        }
    
        public int clienteid { get; set; }
        public string dni { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string mail { get; set; }
        public Nullable<int> segmento { get; set; }
        public string celular { get; set; }
        public Nullable<System.DateTime> fecreg { get; set; }
        public Nullable<int> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MULTIPRODUCTOS_SOLICITUD> MULTIPRODUCTOS_SOLICITUD { get; set; }
    }
}
